[project]
name = "ai-chatbot-js"
version = "1.1.0"
description = "A RAG-based assistant for auction platform support"
authors = [
    { name = "Andrei Dryzgalovich", email = "andrei.d@geomotiv.com" }
]